# Generated by Django 3.0 on 2019-12-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('year', models.TextField()),
                ('genre', models.TextField()),
            ],
        ),
    ]
